# Generated by Django 3.0 on 2019-12-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('spesies', models.CharField(max_length=200)),
                ('berat', models.IntegerField(default=0)),
                ('umur', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kandang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('isi_kandang', models.TextField()),
                ('luas_kandang', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('hari_berkunjung', models.DateTimeField(verbose_name='hari_berkunjung')),
            ],
        ),
        migrations.CreateModel(
            name='Penjaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('jadwal_jaga', models.DateTimeField(verbose_name='jadwal_jaga')),
            ],
        ),
    ]
